server:
  port: 8889
spring:
  profiles:
    active: dev
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    streams:
      application-id: kafka9000-v0.1
      properties: # properties not explicitly handled by KafkaProperties.streams
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
    template:
      default-topic: poc-kafka
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-doc.html
    operations-sorter: method
